import img1 from '../assets/latte.webp'
import img2 from '../assets/pasta1.webp'
import img3 from '../assets/pasta2.webp'
import img4 from '../assets/pasta3.webp'
import img5 from '../assets/pasta4.webp'
import img6 from '../assets/pasta5.webp'
import img7 from '../assets/pasta6.webp'
import img8 from '../assets/pasta7.webp'
import img10 from '../assets/pitza1.webp'
import img11 from '../assets/pitza2.webp'
import img12 from '../assets/masala.webp'
import img13 from '../assets/americanoo.webp'




const myproducts = [
    {
        image: img13,
        title:" اسپرسو",
        id:1,
        category:"بر پایه اسپرسو",
        price:"98.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" آمریکانو",
        id:2,
        category:"بر پایه اسپرسو",
        price:"98.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" لاته",
        id:3,
        category:"بر پایه اسپرسو",
        price:"115.000",
        recepi: "شات اسپرسو + شیر گرم",
    },  {
        image: img13,
        title:" لاته کارامل",
        id:4,
        category:"بر پایه اسپرسو",
        price:"125.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" لاته فندوق",
        id:5,
        category:"بر پایه اسپرسو",
        price:"125.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" لاته دارچین",
        id:6,
        category:"بر پایه اسپرسو",
        price:"125.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" لاته عسل",
        id:7,
        category:"بر پایه اسپرسو",
        price:"125.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" موکا",
        id:8,
        category:"بر پایه اسپرسو",
        price:"135.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" کورتادو",
        id:9,
        category:"بر پایه اسپرسو",
        price:"110.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" فلت وایت",
        id:10,
        category:"بر پایه اسپرسو",
        price:"110.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img11,
        title:"هات چاکلت",
        id:11,
        category:"بار گرم",
        price:"110.000",
        recepi: "  کلم بروکلی ،هویج،کدو،قارچ ،نخود فرنگی خمیر ترش پپرونی",
    },
    {
        image: img11,
        title:"وایت چاکلت",
        id:12,
        category:"بار گرم",
        price:"110.000",
        recepi: "  کلم بروکلی ،هویج،کدو،قارچ ،نخود فرنگی خمیر ترش پپرونی",
    },{
        image: img11,
        title:"ماسالا",
        id:13,
        category:"بار گرم",
        price:"110.000",
        recepi: "  کلم بروکلی ،هویج،کدو،قارچ ،نخود فرنگی خمیر ترش پپرونی",
    },{
        image: img11,
        title:"لاته بیسکوییت",
        id:14,
        category:"بار گرم",
        price:"110.000",
        recepi: "  کلم بروکلی ،هویج،کدو،قارچ ،نخود فرنگی خمیر ترش پپرونی",
    },{
        image: img11,
        title:"لاته پسته",
        id:15,
        category:"بار گرم",
        price:"150.000",
        recepi: "  کلم بروکلی ،هویج،کدو،قارچ ،نخود فرنگی خمیر ترش پپرونی",
    },
    {
        image: img10,
        title:" چای سیاه",
        id:16,
        category:"چای بار",
        price:"50.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img10,
        title:" دمنوش چای سبر لیمو عمانی",
        id:17,
        category:"چای بار",
        price:"60.000",
        recepi: "lorem ipsum is free noot for you",
    },{
        image: img10,
        title:" دمنوش گل گاو زبان ، چای ترش",
        id:18,
        category:"چای بار",
        price:"60.000",
        recepi: "lorem ipsum is free noot for you",
    },{
        image: img10,
        title:" چای انگلیسی",
        id:19,
        category:"چای بار",
        price:"65.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آیس آمریکانو",
        id:20,
        category:"سرد بر پایه اسپرسو",
        price:"98.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آیس لاته",
        id:21,
        category:"سرد بر پایه اسپرسو",
        price:"120.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آیس کارامل ماکیاتو",
        id:22,
        category:"سرد بر پایه اسپرسو",
        price:"125.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آیس لاته فندوق",
        id:23,
        category:"سرد بر پایه اسپرسو",
        price:"125.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آیس لاته دارچین",
        id:24,
        category:"سرد بر پایه اسپرسو",
        price:"125.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آیس لاته عسل",
        id:25,
        category:"سرد بر پایه اسپرسو",
        price:"125.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آفوگاتو",
        id:26,
        category:"سرد بر پایه اسپرسو",
        price:"120.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" فراپاچینو",
        id:27,
        category:"سرد بر پایه اسپرسو",
        price:"120.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img12,
        title:" منیت آلواورا",
        id:28,
        category:"ماکتیل",
        price:"130.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" لیموناد",
        id:29,
        category:"ماکتیل",
        price:"110.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" موهیتو",
        id:30,
        category:"ماکتیل",
        price:"120.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" هات رد",
        id:31,
        category:"ماکتیل",
        price:"؟؟؟.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" پرپل آلوورا",
        id:32,
        category:"ماکتیل",
        price:"130.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" چیلی منگو",
        id:33,
        category:"اسموتی",
        price:"160.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" پانا پینا",
        id:34,
        category:"اسموتی",
        price:"160.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" کوکو منگو",
        id:35,
        category:"اسموتی",
        price:"160.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" رد اورنج",
        id:36,
        category:"اسموتی",
        price:"160.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" شیک میوه",
        id:37,
        category:"شیک ها",
        price:"175.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" شیک شکلات فندوق",
        id:38,
        category:"شیک ها",
        price:"145.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" شیک کرم بیسکوییت",
        id:39,
        category:"شیک ها",
        price:"165.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" شیک پینات اسپرسو",
        id:40,
        category:"شیک ها",
        price:"185.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" شیک بادام زمینی",
        id:41,
        category:"شیک ها",
        price:"145.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img1,
        title:" ماچا لاته شیر عسلی",
        id:42,
        category:"ماچا بار",
        price:"133.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img1,
        title:" ماچا لاته وانیلی",
        id:43,
        category:"ماچا بار",
        price:"133.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img1,
        title:"ماچا منگو",
        id:44,
        category:"ماچا بار",
        price:"133.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
     {
        image: img1,
        title:" تونیک ماچا",
        id:45,
        category:"ماچا بار",
        price:"133.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },

]

export { myproducts };