import img1 from '../assets/latte.webp'
import img2 from '../assets/pasta1.webp'
import img3 from '../assets/pasta2.webp'
import img4 from '../assets/pasta3.webp'
import img5 from '../assets/pasta4.webp'
import img6 from '../assets/pasta5.webp'
import img7 from '../assets/pasta6.webp'
import img8 from '../assets/pasta7.webp'
import img10 from '../assets/pitza1.webp'
import img11 from '../assets/pitza2.webp'
import img12 from '../assets/masala.webp'
import img13 from '../assets/americanoo.webp'




const myproducts = [
    {
        id:1,
        image: img13,
        title:" اسپرسو",
        category:"گرم اسپرسو",
        price:"98.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" آمریکانو",
        id:2,
        category:"گرم اسپرسو",
        price:"98.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" لاته",
        id:3,
        category:"گرم اسپرسو",
        price:"115.000",
        recepi: "شات اسپرسو + شیر گرم",
    },  {
        image: img13,
        title:" لاته کارامل",
        id:4,
        category:"گرم اسپرسو",
        price:"125.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" لاته فندوق",
        id:5,
        category:"گرم اسپرسو",
        price:"125.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" لاته دارچین",
        id:6,
        category:"گرم اسپرسو",
        price:"125.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" لاته عسل",
        id:7,
        category:"گرم اسپرسو",
        price:"125.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" موکا",
        id:8,
        category:"گرم اسپرسو",
        price:"135.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" کورتادو",
        id:9,
        category:"گرم اسپرسو",
        price:"110.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" فلت وایت",
        id:10,
        category:"گرم اسپرسو",
        price:"110.000",
        recepi: "شات اسپرسو + شیر گرم",
    },
    {
        image: img11,
        title:"هات چاکلت",
        id:11,
        category:"بار گرم",
        price:"110.000",
        recepi: "  کلم بروکلی ،هویج،کدو،قارچ ،نخود فرنگی خمیر ترش پپرونی",
    },
    {
        image: img11,
        title:"وایت چاکلت",
        id:12,
        category:"بار گرم",
        price:"110.000",
        recepi: "  کلم بروکلی ،هویج،کدو،قارچ ،نخود فرنگی خمیر ترش پپرونی",
    },{
        image: img11,
        title:"ماسالا",
        id:13,
        category:"بار گرم",
        price:"110.000",
        recepi: "  کلم بروکلی ،هویج،کدو،قارچ ،نخود فرنگی خمیر ترش پپرونی",
    },{
        image: img11,
        title:"لاته بیسکوییت",
        id:14,
        category:"بار گرم",
        price:"110.000",
        recepi: "  کلم بروکلی ،هویج،کدو،قارچ ،نخود فرنگی خمیر ترش پپرونی",
    },{
        image: img11,
        title:"لاته پسته",
        id:15,
        category:"بار گرم",
        price:"150.000",
        recepi: "  کلم بروکلی ،هویج،کدو،قارچ ،نخود فرنگی خمیر ترش پپرونی",
    },
    {
        image: img10,
        title:" چای سیاه",
        id:16,
        category:"چای بار",
        price:"50.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img10,
        title:" دمنوش چای سبر لیمو عمانی",
        id:17,
        category:"چای بار",
        price:"60.000",
        recepi: "lorem ipsum is free noot for you",
    },{
        image: img10,
        title:" دمنوش گل گاو زبان ، چای ترش",
        id:18,
        category:"چای بار",
        price:"60.000",
        recepi: "lorem ipsum is free noot for you",
    },{
        image: img10,
        title:" چای انگلیسی",
        id:19,
        category:"چای بار",
        price:"65.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آیس آمریکانو",
        id:20,
        category:"سرد  اسپرسو",
        price:"98.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آیس لاته",
        id:21,
        category:"سرد  اسپرسو",
        price:"120.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آیس کارامل ماکیاتو",
        id:22,
        category:"سرد  اسپرسو",
        price:"125.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آیس لاته فندوق",
        id:23,
        category:"سرد  اسپرسو",
        price:"125.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آیس لاته دارچین",
        id:24,
        category:"سرد  اسپرسو",
        price:"125.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آیس لاته عسل",
        id:25,
        category:"سرد  اسپرسو",
        price:"125.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" آفوگاتو",
        id:26,
        category:"سرد  اسپرسو",
        price:"120.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img11,
        title:" فراپاچینو",
        id:27,
        category:"سرد  اسپرسو",
        price:"120.000",
        recepi: "lorem ipsum is free noot for you",
    },
    {
        image: img12,
        title:" منیت آلواورا",
        id:28,
        category:"ماکتیل",
        price:"130.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" لیموناد",
        id:29,
        category:"ماکتیل",
        price:"110.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" موهیتو",
        id:30,
        category:"ماکتیل",
        price:"120.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" هات رد",
        id:31,
        category:"ماکتیل",
        price:"؟؟؟.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" پرپل آلوورا",
        id:32,
        category:"ماکتیل",
        price:"130.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" چیلی منگو",
        id:33,
        category:"اسموتی",
        price:"160.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" پانا پینا",
        id:34,
        category:"اسموتی",
        price:"160.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" کوکو منگو",
        id:35,
        category:"اسموتی",
        price:"160.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img12,
        title:" رد اورنج",
        id:36,
        category:"اسموتی",
        price:"160.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" شیک میوه",
        id:37,
        category:"شیک",
        price:"175.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" شیک شکلات فندوق",
        id:38,
        category:"شیک",
        price:"145.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" شیک کرم بیسکوییت",
        id:39,
        category:"شیک",
        price:"165.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" شیک پینات اسپرسو",
        id:40,
        category:"شیک",
        price:"185.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img13,
        title:" شیک بادام زمینی",
        id:41,
        category:"شیک",
        price:"145.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img1,
        title:" ماچا لاته شیر عسلی",
        id:42,
        category:"ماچا بار",
        price:"133.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img1,
        title:" ماچا لاته وانیلی",
        id:43,
        category:"ماچا بار",
        price:"133.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img1,
        title:"ماچا منگو",
        id:44,
        category:"ماچا بار",
        price:"133.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
     {
        image: img1,
        title:" تونیک ماچا",
        id:45,
        category:"ماچا بار",
        price:"133.000",
        recepi: "2شات اسپرسو + شیر گرم",
    },
    {
        image: img1,
        title:"پیتزا سیر و استیک",
        id:46,
        category:"پیتزا",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"پیتزا استیک و مارینارا",
        id:47,
        category:"پیتزا",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"پیتزا مرغ آلفردو",
        id:48,
        category:"پیتزا",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"پیتزا بو قلمون پستو",
        id:49,
        category:"پیتزا",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"لازانیا بلونز",
        id:50,
        category:"غدای اصلی",
        price:"380.000",
        recepi: "",
    },
    {
        image: img1,
        title:" استیک",
        id:51,
        category:"غدای اصلی",
        price:"650.000",
        recepi: "",
    },
    {
        image: img1,
        title:"موساکو",
        id:52,
        category:"غدای اصلی",
        price:"320.000",
        recepi: "",
    },
    {
        image: img1,
        title:"مرغ با سس زرشک",
        id:53,
        category:"ساندویچ",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"بوقلمون و پستو",
        id:54,
        category:"ساندویچ",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"بیف و سس پیاز",
        id:55,
        category:"ساندویچ",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"مارگاریتا",
        id:56,
        category:"ساندویچ",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"تاکو استیک",
        id:57,
        category:"ساندویچ",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"تاکو مرغ",
        id:58,
        category:"ساندویچ",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"تاکو سبزیجات",
        id:59,
        category:"ساندویچ",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"آلفردو / مرغ -گوشت",
        id:60,
        category:"پاستا",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"پستو / مرغ",
        id:61,
        category:"پاستا",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"فتوچینی میت بال با سس مارینا را",
        id:62,
        category:"پاستا",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"فتوچینی  سبزیجات",
        id:63,
        category:"پاستا",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"سالاد سوخاری",
        id:64,
        category:"سالاد",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"سالاد گرین",
        id:65,
        category:"سالاد",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"سالاد بیف",
        id:66,
        category:"سالاد",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"جوسی برگر",
        id:67,
        category:"برگر",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"چیز برگر",
        id:68,
        category:"برگر",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"برگر ساده",
        id:69,
        category:"برگر",
        price:"133.000",
        recepi: "",
    },
    {
        image: img1,
        title:"سیب زمینی",
        id:70,
        category:"پیش غدا",
        price:"150.000",
        recepi: "",
    },
    {
        image: img1,
        title:"سیب زمینی با سس آلفردو ",
        id:71,
        category:"پیش غدا",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"سیب زمینی با دیپ چدار",
        id:72,
        category:"پیش غدا",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"بروسکتا",
        id:73,
        category:"پیش غدا",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"دیپ لوبیا",
        id:74,
        category:"پیش غدا",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"املت مارینارا",
        id:75,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"املت فرانک فورتر",
        id:76,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:" املت شوید پنیر",
        id:77,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"خرما گردو",
        id:78,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"ترکی",
        id:79,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"اسپانیایی",
        id:80,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"انگلیسی",
        id:81,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"فرنچ تست",
        id:82,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"اسکرمبل بیکن",
        id:83,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"اسکرمبل سبزیجات",
        id:84,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"سیمیت بوقلمون گردو",
        id:85,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"سیمیت مارگاریتا",
        id:86,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"تست آواکادو",
        id:87,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"تست بیکن",
        id:88,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"داچ بیبی",
        id:89,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"تست بیکن",
        id:90,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },
    {
        image: img1,
        title:"صبحانه رژیمی",
        id:91,
        category:"صبحانه",
        price:"185.000",
        recepi: "",
    },




]

export { myproducts };